### ISSUE TITLE
Tranquility ingestion fails to work with Druid Cluster enforcing TLS.

### ISSUE THREAD

**Issue by himanshug** [druid-io/tranquility#255]
It needs to be investigated whether Tranquility currently handles getting ssl ports from DruidNode announcements and able to appropriate send 'https' requests with right port. Fixes, if necessary, are required to be done.

**Comment by pjain1** [comment]
So I looked briefly at tranquility code and here's what I think needs to be modified to support tls -
1. Make changes to DiscoResolver [here](https://github.com/metamx/scala-util/blob/master/src/main/scala/com/metamx/common/scala/net/finagle/DiscoResolver.scala#L31) to use sslPort is present.
2. Make changes to IndexService [here](https://github.com/druid-io/tranquility/blob/master/core/src/main/scala/com/metamx/tranquility/druid/IndexService.scala#L215) to prefer tlsPort from TaskLocation object if present so that DruidTaskResolver prefers sslPort.
3. Create a custom FinagleRegistry which adds `.tls(SSLContext)` to the ClientBuilder and use that for creating the beam. I believe the `dest` and `codec` configs for ClientBuilder remains the same. Currently, these are set to -
```
.codec(http.Http())
.dest(Name.Bound(resolver.bind(name), id))
```
@gianm any opinions ?

**Comment by gianm** [comment]
@pjain1 that sounds right to me -- some testing may reveal other stuff that has to change, but the points you found are a good start. May also want to update finagle while doing that, in case the newer versions work better with tls.

On point (1) though, I know that @himanshug had suggested implementing coordinator based service discovery for Tranquility, so it doesn't have to use Curator discovery. See https://github.com/druid-io/tranquility/issues/251 for more details. If that was done first then we could make TLS depend on No-ZK discovery, and then DiscoResolver changes won't be necessary. (DiscoResolver is only needed for ZK based Curator discovery)

**Comment by himanshug** [comment]
@gianm @pjain1 I think we should keep coordinator based service discovery independent of this change as most users are using zk directly. in any case, we need to continue supporting CuratorDiscovery given that coordinator end point would only show up in 0.11.1 Druid. https://github.com/druid-io/tranquility/issues/251 resolution is not as important right now as this one. Also, even if Tranquility supports discovering tasks from overlord already but no-one is actually using that (because that is not default) so not sure how well that works.
