### ISSUE TITLE
Tranquility master on druid-0.9.2.  druid now building druid-0.12.3

### ISSUE THREAD

**Issue by windbender** [druid-io/tranquility#284]
So druid version 0.9.2 was released around December 2016.  Here we are almost 2 years later and the master branch of tranquility is still building against druid 0.9.2.  Meanwhile, druid is latest is 0.12.3. and has 0.13 in SNAPSHOT.  I saw a branch for druid 0.10.

I'm curious what is going on.  Is this a lack of time on the part of maintainers, or is this a fundamental change in direction with druid which means tranquility doesn't "fit" anymore ?

I'm interested in building a system which will stream data into druid.  It seems that tranquility would be the right solution to build this, but also seems like it's not getting a lot of attention recently.  Any recommendation?

**Comment by jon-wei** [comment]
Hi @windbender,

> I'm curious what is going on. Is this a lack of time on the part of maintainers, or is this a fundamental change in direction with druid which means tranquility doesn't "fit" anymore ?

It's more of the latter, for streaming ingestion we've been moving away from Tranquility's "push" model to the "pull" model used by the Kafka Indexing Service (http://druid.io/docs/latest/development/extensions-core/kafka-ingestion) which has a lot of development activity, I think we would recommend using that instead for new deployments with streaming requirements.

Tranquility will still work with the current version of Druid (0.12.3), the Druid APIs it uses (submitting tasks, getting task status, and pushing events to peons) haven't really changed since 0.9.2, so there hasn't been a need to have it build against a newer version of Druid so far.

**Comment by windbender** [comment]
Ok, I'll take a deeper looking at using Kafka.

So that I'm clear, you are saying that I should be able to use tranquility built against 0.9.2. to stuff data into druid 0.12.3 ?

**Comment by jon-wei** [comment]
> So that I'm clear, you are saying that I should be able to use tranquility built against 0.9.2. to stuff data into druid 0.12.3 ?

Yes, that'll work (there's a tutorial example for that actually): http://druid.io/docs/0.12.3/tutorials/tutorial-tranquility.html

The new 0.8.3 version of Tranquility that was just released also supports connecting to TLS-enabled Druid clusters, and can optionally provide Basic HTTP user/pass authentication credentials when communicating with Druid.

**Comment by linhao1990** [comment]
> > So that I'm clear, you are saying that I should be able to use tranquility built against 0.9.2. to stuff data into druid 0.12.3 ?
> 
> Yes, that'll work (there's a tutorial example for that actually): http://druid.io/docs/0.12.3/tutorials/tutorial-tranquility.html

Tranquility 0.8.2 works for druid 0.12.0 at most of the time, but may fail to create task for aggregators like 'quantilesDoublesSketch' which is introduced since druid 0.12.

We use the following command to run tranquility task:
`/usr/lib/tranquility/bin/tranquility kafka -configFile /usr/lib/tranquility/data_sketch_test.json  -Ddruid.extensions.loadList='["druid-datasketches"]' -Ddruid.extensions.directory=/usr/lib/druid-0.9.2/extensions`

It fails with the following error:
`Could not resolve type id 'quantilesDoublesSketch' into a subtype of [simple type, class io.druid.query.aggregation.AggregatorFactory]`

If we try to run tranquility with  `-Ddruid.extensions.directory=/usr/lib/druid-extension-0.12.3`, it will fail with another error:
`java.lang.NoClassDefFoundError: Could not initialize class com.metamx.tranquility.druid.DruidGuicer`

I know is's caused by extension library with different versions. Now how can we use Tranquility to build a segment with `quantilesDoublesSketch` aggregator?

**Comment by windbender** [comment]
Thanks
