### ISSUE TITLE
ClusteredBeamTuning rejectionPolicy

### ISSUE THREAD

**Issue by eyalgo** [druid-io/tranquility#51]
Hi,
I tried to set window period for 1 year (windowPeriod = new Period("P1Y")).
We need this as sometimes we might to re-index our data.

I got the following error from druid: java.lang.UnsupportedOperationException, exceptionMessage=Cannot convert to Duration as this period contains years and years vary in length}

I guess it's not valid to send 1 year.

So I wanted to set rejectionPolicy in the tuning to 'none'.
But this option is not available.
I there a plan to add rejection to the tuning?

Thanks

**Comment by gianm** [comment]
Hey @eyalgo, due to the way tranquility works, it must use a specific rejection policy that involves a windowPeriod. The rationale is described in the doc here: https://github.com/druid-io/tranquility/blob/master/docs/overview.md

We intend to change this in the future, see https://github.com/druid-io/druid/issues/1642. But for now it is a limitation.
